version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - ls -lrt
      - cd CodePipeline/p1-lambda
      - sam build
      - pip install -r requirements.txt -t lib
      - export BUCKET_NAME=test-pipeline-output-bucket-milind
      - sam package --s3-bucket $BUCKET --output-template-file output-template.yaml

      #- aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET_NAME --output-template-file output-template.yaml
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      # - zip -r9 ../deployment_package1.zip .
      - cd ..
      - ls -lrt
      - cd indexLambdaFunction
      - zip -g ../deployment_package.zip lambda_function.py
      # - cd ../lf2a2
      # - zip -g ../deployment_package1.zip lambda_function.py
      - cd ..
      - ls -lrt
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - ls -lrt
      - aws lambda update-function-code --function-name test-function --zip-file fileb://deployment_package.zip
      #- aws lambda update-function-code --function-name search-photos --zip-file fileb://deployment_package1.zip
      - echo "Done!"
      - echo $CODEBUILD_SRC_DIR
      - ls -lrt $CODEBUILD_SRC_DIR

artifacts:
  type: zip
  files:
    - "CodePipeline/p1-lambda/template.yaml"
    - "CodePipeline/p1-lambda/output-template.yaml"
