version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - ls -lrt
      - cd CodePipeline/p1-lambda
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      # - zip -r9 ../deployment_package1.zip .
      - cd ..
      - ls -lrt
      - cd indexLambdaFunction
      - zip -g ../deployment_package.zip lambda_function.py
      # - cd ../lf2a2
      # - zip -g ../deployment_package1.zip lambda_function.py
      - cd ..
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name test-function --zip-file fileb://deployment_package.zip
      #- aws lambda update-function-code --function-name search-photos --zip-file fileb://deployment_package1.zip
      - echo "Done!"
