AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Python file including external library

Resources:
  SampleFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Role: arn:aws:iam::438830062189:role/service-role/index-photos-role-282pylm3
      FunctionName: index-photos
      MemorySize: 512
      Timeout: 60
      Handler: lambda_function.handler
      Runtime: python3.8
      CodeUri: ./indexLambdaFunction
#Resources:
# SampleFunction:
#  Type: AWS::Serverless::Function
#  Properties:
#    Handler: index.lambda_handler
#    Runtime: python3.7
#    FunctionName: SamplePython
#    CodeUri: ./src #Directory the source file is
